# Generated by Django 5.0.1 on 2024-02-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiquorStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquor_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('quantity_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquor_name', models.CharField(max_length=255)),
                ('stock_sold', models.PositiveIntegerField()),
                ('quantity_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
